# https://github.com/thedodd/trunk/blob/master/Trunk.toml

[serve]
# The address to serve on.
address = "0.0.0.0"
# The port to serve on.
port = 3002

[[proxy]]
rewrite = "/api"
# TODO: use envvar instead of hardcoding
backend = "http://localhost:8000/api"
